name: Zomato Stock Predictor Automation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: 3.10  # Specify Python version 3.10 for compatibility with TensorFlow
        architecture: x64  # Use 64-bit architecture (default)
        check-latest: true  # Ensure it checks for the latest compatible version
        cache: pip  # Use pip for dependency caching
        cache-dependency-path: 'requirements.txt'  # Path to dependencies for caching
        update-environment: true  # Update environment variables

          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run daily script
      run: |
        python daily_run.py

    - name: Commit changes
      run: |
        git config --global user.name "abizer007"
        git config --global user.email "abizermasavi@gmail.com"
        git add .
        git commit -m "Daily automation: $(date +'%Y-%m-%d')"
        git push
