name: Zomato Stock Predictor Automation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-22.04


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies and tools
      run: |
        pip install -r requirements.txt
        pip install flake8 pytest gitpython

    - name: Lint with flake8
      run: flake8 .

    - name: Run tests
      run: pytest

    - name: Run daily prediction script
      run: python daily.py

    - name: Generate prediction plot
      run: python graphical.py

    - name: Check if plot file exists
      run: ls -l logs/predictions_plot.png

    - name: Upload prediction plot
      uses: actions/upload-artifact@v3
      with:
        name: predictions_plot
        path: logs/predictions_plot.png
        if-no-files-found: warn

    - name: Configure git and commit changes
      run: |
        git config --global user.name "abizer007"
        git config --global user.email "abizermasavi@gmail.com"
        git remote set-url origin https://github-actions:${{ secrets.ZOM_TOK }}@github.com/abizer007/zomato-stock-predictor.git
        git add performance.txt weekly_predictions.txt monthly_predictions.txt yearly_predictions.txt stock_data.csv

        if git diff --cached --quiet; then
          echo "✅ No changes to commit."
        else
          git commit -m "📈 Daily automation: $(date +'%Y-%m-%d')"
          git push
        fi

