name: Zomato Stock Predictor Automation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run daily script
      run: |
        python daily.py

    - name: Commit predictions
      run: |
        git config --global user.name "abizer007"
        git config --global user.email "abizermasavi@gmail.com"
        git add weekly_predictions.txt
        git commit -m "Daily automation: $(date +'%Y-%m-%d')"
        git push

